let tag_new=document.createElement('p')
document.body.appendChild(tag_new)
tag_new.appendChild(document.createTextNode('hi'))
tag_new.setAttribute('id', 'zeynab')
tag_new.setAttribute('class', 'zeynab')